import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/providers";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(geistSans.variable, geistMono.variable, "antialiased")}
            >
                <Providers>
                    <div className="font-[family-name:var(--font-geist-sans)] flex flex-col items-center">
                        <Navbar />
                        <main className="container px-4 py-10 w-full max-w-7xl mx-auto">{children}</main>
                    </div>
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
